---
- name: Rotate SSH Keys
  hosts: ubuntu
  vars:
   - new_pub_key: ~/.ssh/id_rsa_new.pub
   - new_priv_key: ~/.ssh/id_rsa_new
  tasks:
   - name: Add new key to authorized_keys
     authorized_key: 
      key="{{lookup('file','/home/opstree/.ssh/id_rsa_new.pub')}}"
      user=root
      state=present

   - name: Make use of new private key when connecting
     set_fact: ansible_private_ssh_key=id_rsa_new.pub

   - name: Make our new key exclusive
     authorized_key: 
      key="{{lookup('file','/home/opstree/.ssh/id_rsa_new.pub')}}"
      user=root 
      state=present 
      exclusive=yes
