---
# tasks file for day10-java_jdk

- name: Install Java JDK in Ubuntu
  apt: 
    name: default-jdk
    state: latest
  when: ansible_os_family == "Debian"

- name: Install Java JDK in Centos
  yum: 
    name: java-1.8.0-openjdk.x86_64
    state: latest
  when: ansible_os_family == "RedHat"
